sylius_grid:
    grids:
        asdoria_admin_marketing_cart:
            driver:
                name: doctrine/orm
                options:
                    class: "%asdoria.model.marketing_cart.class%"
            sorting:
                updatedAt: desc
            fields:
                image:
                    type: twig
                    label: sylius.ui.image
                    path: .
                    options:
                        template: "@AsdoriaSyliusMarketingCartPlugin/Admin/Grid/Field/image.html.twig"
                slug:
                    type: string
                    label: asdoria.ui.slug
                name:
                    type: string
                    label: sylius.ui.name
                criteria:
                    type: twig
                    label: asdoria.ui.criteria
                    sortable: ~
                    path: .
                    options:
                        template: "@AsdoriaSyliusMarketingCartPlugin/Admin/Grid/Field/criteria.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                highlighted:
                    type: twig
                    label: asdoria.ui.highlighted
                    sortable: ~
                    options:
                        template: "@AsdoriaSyliusMarketingCartPlugin/Admin/Grid/Field/highlighted.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                updatedAt:
                    type: datetime
                    label: asdoria.ui.updated_at
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    archive:
                        type: archive
            filters:
                criteria:
                    type: string
                    label: asdoria.ui.criteria
                channels:
                    type: entity
                    label: sylius.ui.channels
                    form_options:
                        class: "%sylius.model.channel.class%"
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
                archival:
                    type: exists
                    label: sylius.ui.archival
                    options:
                        field: archivedAt
                    default_value: false
