services:
    asdoria.marketing_cart.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        parent: "sylius.listener.images_upload"
        public: false
        tags:
            - { name: kernel.event_listener, event: asdoria.marketing_cart.pre_create, method: uploadImages }
            - { name: kernel.event_listener, event: asdoria.marketing_cart.pre_update, method: uploadImages }
