services:
    Asdoria\SyliusMarketingCartPlugin\Menu\AdminMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: !php/const Sylius\Bundle\AdminBundle\Menu\MainMenuBuilder::EVENT_NAME, method: addAdminMenuItems }

    Asdoria\SyliusMarketingCartPlugin\Menu\MarketingCartFormMenuBuilder:
        public: true
        arguments:
            $factory: '@knp_menu.factory'
            $eventDispatcher: '@event_dispatcher'
        tags:
            - { name: knp_menu.menu_builder, method: createMenu , alias: 'asdoria_marketing.admin.marketing_cart_form' }
