asdoria_shop_marketing_cart_ajax:
    resource: "shop/ajax.yaml"
    prefix: /ajax

asdoria_shop_marketing_cart_index:
    path: /marketing-cart
    methods: [GET, POST]
    defaults:
        _controller: Asdoria\SyliusMarketingCartPlugin\Controller\Shop\MarketingCartController
