framework:
    assets:
        packages:
            asdoria_sylius_marketing_cart_plugin:
                base_path: '/bundles/asdoriasyliusmarketingcartplugin'

imports:
    - "@AsdoriaSyliusMarketingCartPlugin/Resources/config/grids/*.yaml"


jms_serializer:
    metadata:
        directories:
            asdoria-sylius-marketing-cart-plugin:
                namespace_prefix: "Asdoria\\SyliusMarketingCartPlugin"
                path: "@AsdoriaSyliusMarketingCartPlugin/Resources/config/serializer"

sylius_ui:
    events:
        asdoria.admin.index_marketing_cart.update.stylesheets:
            blocks:
                comparator:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Admin/_stylesheets.html.twig"
                    priority: 5

        asdoria.admin.index_marketing_cart.update.javascripts:
            blocks:
                comparator:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Admin/_javascripts.html.twig"
                    priority: 5
        asdoria.admin.index_marketing_cart.create.stylesheets:
            blocks:
                comparator:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Admin/_stylesheets.html.twig"
                    priority: 5

        asdoria.admin.index_marketing_cart.create.javascripts:
            blocks:
                comparator:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Admin/_javascripts.html.twig"
                    priority: 5

        asdoria.shop.marketing_cart.header:
            blocks:
                breadcrumb:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Shop/MarketingCart/Header/_breadcrumb.html.twig"
                    priority: 20
                header:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Shop/MarketingCart/Header/_content.html.twig"
                    priority: 10
                similar_carts:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Shop/MarketingCart/Header/_similarCarts.html.twig"
                    priority: 5

        asdoria.shop.marketing_cart.index.search:
            blocks:
                search:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Shop/MarketingCart/Index/_search.html.twig"
                    priority: 30
                pagination:
                    template: "@SyliusShop/Product/Index/_pagination.html.twig"
                    priority: 20
                sorting:
                    template: "@SyliusShop/Product/Index/_sorting.html.twig"
                    priority: 10

        sylius.shop.homepage:
            blocks:
                latest_marketing_carts:
                    template: "@AsdoriaSyliusMarketingCartPlugin/Shop/Homepage/_latestMarketingCarts.html.twig"
                    priority: 45
