asdoria_maketing_shop_partial_maketing_cart_show_by_slug:
    path: /by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: asdoria.controller.marketing_cart::showAction
        _sylius:
            template: $template
            repository:
                method: findOneBySlug
                arguments:
                    slug: $slug
                    locale: "expr:service('sylius.context.locale').getLocaleCode()"
                    channel: "expr:service('sylius.context.channel').getChannel()"
    requirements:
        slug: .+

asdoria_maketing_shop_partial_maketing_cart_index_highlighted_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: asdoria.controller.marketing_cart::indexAction
        _sylius:
            template: $template
            repository:
                method: findLatestByChannelAndHighlighted
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - '!!int $count'
